version: '3.4'

services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SuperSecret
      MYSQL_USER: TuringUsr
      MYSQL_PASSWORD: ThisIsAPassword
      MYSQL_DATABASE: Turing
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysqlscript:/docker-entrypoint-initdb.d
    ports:
     - 3306
  turingapi:
    depends_on:
      - mysql
    image: ${DOCKER_REGISTRY-}turingapi
    build:
      context: .
      dockerfile: TuringApi/Dockerfile
volumes:
  dbdata: